#!/bin/bash
rm -rf lua_modules/*
#luarocks --lua-version=5.1 --tree lua_modules install pgmoon
luarocks --lua-version=5.1 --tree lua_modules install sha2 &&
	luarocks --lua-version=5.1 --tree lua_modules install md5 &&
	luarocks --lua-version=5.1 --tree lua_modules install lbase64 &&
	luarocks --lua-version=5.1 --tree lua_modules install lua-resty-uuid &&
	luarocks --lua-version=5.1 --tree lua_modules install lua-resty-exec &&
	luarocks --lua-version=5.1 --tree lua_modules install lua-resty-session &&
	luarocks --lua-version=5.1 --tree lua_modules install lua-resty-http &&
	luarocks --lua-version=5.1 --tree lua_modules install lua-resty-mail &&
	luarocks --lua-version=5.1 --tree lua_modules install lua-resty-reqargs &&
	luarocks --lua-version=5.1 --tree lua_modules install net-url &&
	luarocks --lua-version=5.1 --tree lua_modules install aspect &&
	luarocks --lua-version=5.1 --tree lua_modules install luafilesystem &&
	luarocks --lua-version=5.1 --tree lua_modules install web_sanitize &&
	luarocks --lua-version=5.1 --tree lua_modules install lua-discount &&
	luarocks --lua-version=5.1 --tree lua_modules install inspect &&
	mkdir -p lua_modules/ext/lua &&
		cd lua_modules/ext/ &&
		wget https://github.com/openresty/lua-resty-memcached/archive/refs/tags/v0.17.tar.gz &&
		tar zxpvf v0.17.tar.gz && cp lua-resty-memcached-0.17/lib/resty/memcached.lua lua/memcached.lua &&
		rm -rf lua-resty-memcached-0.17 && rm -f v0.17.tar.gz


