#!/bin/bash
BACK=$(find ./src/back -type f -exec md5sum {} \; | sort -k 2 | md5sum)
FRONT=$(find ./src/front -type f -exec md5sum {} \; | sort -k 2 | md5sum)
SHARED=$(find ./src/shared -type f -exec md5sum {} \; | sort -k 2 | md5sum)
DIST=$(find ./src/dist -type f -exec md5sum {} \; | sort -k 2 | md5sum)

while true
do
	back=$(find ./src/back -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	if [ "$back" != "$BACK" ]; then
		make slick
		BACK=$(find ./src/back -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	fi

	front=$(find ./src/front -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	if [ "$front" != "$FRONT" ]; then
		make moonro
		make moonro-clean
		FRONT=$(find ./src/front -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	fi

	shared=$(find ./src/shared -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	if [ "$shared" != "$SHARED" ]; then
		make slick
		make moonro
		make moonro-clean
		SHARED=$(find ./src/shared -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	fi
	
	dist=$(find ./src/dist -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	if [ "$dist" != "$DIST" ]; then
		make slick
		make moonro
		make moonro-clean
		DIST=$(find ./src/dist -type f -exec md5sum {} \; | sort -k 2 | md5sum)
	fi

	sleep 1
done

